version: '2'
services:
  django:
    extends:
      file: ./docker/compose-common.yml
      service: django
    links:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=pyconcz_2016.settings_dev

  webpack:
    build:
      context: .
      dockerfile: ./docker/webpack.docker
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      - POSTGRES_USER=pyconcz
